Rasto
H00N24/PV056-AutoML-testing-framework pull request #1
Opened 2019-03-11 17:06 UTC by rastislavpapco

F3 F4 measure, nie som si isty ale ci to netreba prerobit do samostatnej classy ako to robili ostatni

2019-03-11 17:27 UTC, H00N24 reviewed
Ahoj, prosím ťa pošleš mi odkaz na článok z ktorého to implementuješ (ideálne aj presnú časť)? Ďakujem.

2019-03-11 17:27 UTC, H00N24 commented on .gitignore
> +.idea/workspace.xml
Takto ignoruješ iba jeden subór ale kopec ďalších sa pridalo do repa. Je potrebné to vyriešiť.
```suggestion
.idea/*
```

2019-03-11 17:27 UTC, H00N24 commented on .gitignore
> +.idea/workspace.xml
Tak isto prosím odstráň všetky súbory  z `.idea/` (stačí iba z commitov).

2019-03-25 21:53 UTC, halficek commented on .gitignore
> +.idea/*
remove .gitignore file from commit.

2019-03-25 21:53 UTC, halficek requested changes
Add Methods description in README.

2019-04-02 19:26 UTC, merged